# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enigma < Formula
  desc ""
  homepage "https://github.com/pipethedev/enigma"
  version "0.1"

  on_macos do
    url "https://github.com/pipethedev/enigma/releases/download/v0.1/enigma_0.1_darwin_all.tar.gz"
    sha256 "25e4f9531cc108b213bb1bca3c14f7cb85e7b6748607c2b95abe4532fc647833"

    def install
      bin.install "enigma"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pipethedev/enigma/releases/download/v0.1/enigma_0.1_linux_arm64.tar.gz"
      sha256 "b53927cfec6659894e588ab523ede926d97f958301964ad56dfcb86f99671a99"

      def install
        bin.install "enigma"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pipethedev/enigma/releases/download/v0.1/enigma_0.1_linux_amd64.tar.gz"
      sha256 "6df78d89ff60f6122ad49bab84268623c9c76cc4f74e0d7f2829f61cfad31bc0"

      def install
        bin.install "enigma"
      end
    end
  end
end
